### PR TITLE
Re-writing Achievement Carousel

### PR DESCRIPTION
**Pull request by aswinidev**
## Description

Achievement Carousel
PS: This is just an initial commit. There is more work left that needs to be done like adding controls and touch functionality.

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code )
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by king-11** [comment]
This doesn't seem to work at all on the mobile screen I am not seeing any achievement just a blank slate

**Comment by aswinidev** [comment]
> This doesn't seem to work at all on the mobile screen I am not seeing any achievement just a blank slate

It's actually a draft right now. I m still working it.. I will let you know when it's ready.

**Comment by king-11** [comment]
Been too long lets get this done by this Friday only

**Comment by aswinidev** [comment]
Closing this PR because it has conflicts

**Pull request closed without merging**
