### PR TITLE
Add Inter IIT achivements

### PR DESCRIPTION
**Pull request by ankur12-1610**
## Description

Add Inter IIT achivements

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring Old Code ( non-breaking change replacing already existing code )
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@king-11 kindly review!

**Comment by king-11** [comment]
22 participating IITs and the location of inter iit needs to be right after lfx 2023 spring?

**Comment by ankur12-1610** [comment]
> 22 participating IITs and the location of inter iit needs to be right after lfx 2023 spring?

Agh! sorry, which means we need to change as well - https://github.com/COPS-IITBHU/sdg-site/blob/abc884772b3a29ffaee6e700953a008ae28a155f/content/achievements/achievements.json#LL116C1-L117C1

Inter IIT was in Feb, LFX results were announced in March, so it should be before LFX Spring.

**Comment by king-11** [comment]
Right LGTM ✨ I don't really know whether delhi participated in the prior inter IITs or not but let's just keep 22.

**Review by king-11 — APPROVED** [review]

**Pull request merged**
