### PR TITLE
about Us Page

### PR DESCRIPTION
**Pull request by debarati-06**
## Fixes

Fixes #[issue number] by @[issue author]

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code )
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Manan-Rathi — CHANGES_REQUESTED** [review]

**Comment by king-11** [comment]
@debarati-06 @jyshdewangan updates on this PR

**Comment by debarati-06** [comment]
> @debarati-06 @jyshdewangan updates on this PR

We are currently making the requested changes and waiting for @tiger-yash to review the PR so we can make all reviewed changes all together.

**Comment by king-11** [comment]
meanwhile take a merge for conflict

**Comment by tiger-yash** [comment]
> > @debarati-06 @jyshdewangan updates on this PR
> 
> We are currently making the requested changes and waiting for @tiger-yash to review the PR so we can make all reviewed changes all together.

Please commit the requested changes and we will review it again once more to review it once more if anything new comes up, also resolve the merge conflict.

**Comment by tiger-yash** [comment]
@debarati-06 please resolve the merge conflicts

**Review by tiger-yash — APPROVED** [review]
LGTM 🚀

**Review by Manan-Rathi — APPROVED** [review]

**Review by king-11 — APPROVED** [review]

**Comment by king-11** [comment]
Thanks @tiger-yash @Manan-Rathi will merge this today morning as soon as am out of blanket :P

**Comment by king-11** [comment]
@all-contributors add @debarati-06 for code and bug fix

**Comment by king-11** [comment]
@all-contributors add @Manan-Rathi for code review

**Comment by king-11** [comment]
@all-contributors add @jyshdewangan for code

**Comment by king-11** [comment]
@all-contributors add @Arvind0302  for code

**Comment by king-11** [comment]
@all-contributors add @MohitSharma-21  for code and maintainance

**Comment by king-11** [comment]
Was able to take a look now only amazing job guys everyone involved @jyshdewangan @MohitSharma-21 @debarati-06 @Arvind0302 🥇 🥳 ...

@nishantwrp you might want to take a look at the current deployment after this PR looking good just left with teams page.

**Pull request merged**
