### PR TITLE
Fix team member avatar

### LINKED ISSUE #104: BUG: No default avatar on Team Page
There is no default avatar for a team member in the Team page.

## Expected Behavior

If the avatar image can't be fetched, then instead a simple avatar with the initials of the team member must be shown.

## Current Behavior

image

## Possible Solution

Place a check to see if the image can be loaded, and if not, use a third-party library to create a Avatar from the initials of the user and display it.

### PR DESCRIPTION
**Pull request by EshaanAgg**
## Description
If the avatar image can't be fetched, then instead a simple avatar with the initials of the team member is shown.

## Fixes

Fixes #104 by @EshaanAgg
## Types of changes

- [X] Bug/Hot fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code )
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read the **CONTRIBUTING** guidelines in repository.
- [X] My pull request has a descriptive title and is attached to an existing issue.
- [X] I haven't repeated the code and it follows established code style of repository.
- [X] My branch is up-to-date with upstream branch.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by IamEzio** [comment]
@EshaanAgg I cannot see the changes in the netlify preview. PTAL

**Comment by EshaanAgg** [comment]
The differences can be seen for two members - Yash Prakash and Ravidev Pandey.
Attaching the relevant screenshots:

## Before 
image
image

## Current
image
image

**Comment by IamEzio** [comment]
The changes look fine but they are not visible on the [deploy preview](https://deploy-preview-106--cops.netlify.app/). Just wanna make sure that they don't actually break the site instead of adding a new feature. Take a look on it and try to fix it if possible. Its not the case with netlify being not able to access GitHub api because the team page loads perfectly well on the deploy preview of other PRs.

**Comment by EshaanAgg** [comment]
The screenshots that I have attached are from the deploy preview itself.
image
Can't seem to find a reason that they won't be visible to you.

**Pull request closed without merging**
